git_config_global:
  # Common options
  user.name: Alex Thompson

  # Aliases
  alias.br: branch --list
  alias.cb: rev-parse --abbrev-ref HEAD
  alias.co: checkout
  alias.nb: "!f() { git checkout -b ${GIT_BRANCH_PREFIX}${1}; }; f"
  alias.pc: "!f() { git push --set-upstream $(git remote) $(git rev-parse --abbrev-ref HEAD); }; f"
  alias.peek: "!f() { git diff HEAD~${1:-1}; }; f"
  alias.pf: push --force-with-lease
  alias.pop: "!f() { git reset HEAD~${1:-1}; }; f"
  alias.pp: pull --prune
  alias.ri: "!f() { git rebase -i HEAD~${1:-1}; }; f"
  alias.st: status --ignore-submodules=dirty
  alias.sync: "!git pp && git tidy"
  alias.tidy: '!git branch --format ''%(refname:short) %(upstream:track)'' | awk ''$2 == "[gone]" { print $1}'' | xargs -r git branch -D'

git_ignore_patterns_global:
  - ".DS_Store"
  - "*.code-workspace"
  - ".vscode/"
  - "*.sublime-*"
  - ".python-version"
  - "__pycache__/"
  - "*.py[cod]"
  - "*$py.class"
  - ".cache/"
  - ".eggs/"
  - "*.egg-info/"
  - "dist/"
  - ".tox/"
  - ".coverage/"
  - "venv/"
  - "*.envrc"
  - ".mypy_cache"
  - ".pytest_cache"
  - "node_modules"
  - ".direnv/"

zplug_packages:
  romkatv/powerlevel10k:
    use: powerlevel10k.zsh-theme
    as: theme
  apt-itude/p10k-config:
  zsh-users/zsh-completions:
  zdharma/fast-syntax-highlighting:
  peterhurford/up.zsh:
  plugins/docker:
    from: oh-my-zsh
  plugins/python:
    from: oh-my-zsh
  plugins/poetry:
    from: oh-my-zsh

zplug_variables:
  DEFAULT_USER: athompson

zsh_aliases:
  ls: ls --color=auto
  ll: ls -lsF
  la: ls -lsaF
  grep: grep --color=auto
  cl: clear

zsh_functions:
  subdiff: |
    subdiff() {
        subl -n --wait "$1" "$2" --command "sublimerge_diff_views {\"left_read_only\": true, \"right_read_only\": true}"
    }

zsh_keybindings:
  "\\^U": backward-kill-line

zsh_options:
  - APPEND_HISTORY
  - EXTENDED_HISTORY
  - HIST_IGNORE_ALL_DUPS
  - HIST_IGNORE_SPACE
  - INTERACTIVE_COMMENTS

zsh_variables:
  HISTFILE: "${HOME}/.zhistory"
  HISTSIZE: 10000
  SAVEHIST: 10000
  EDITOR: "subl --wait"
  KUBE_EDITOR: "subl --wait"
  PIP_REQUIRE_VIRTUALENV: "true"

pyenv_versions:
  3.10.6:
    global: true

rbenv_versions:
  2.7.6:
    global: true
