git_config_global:
  # Diff and merge tools
  core.editor: subl -n --wait
  diff.tool: vscode
  difftool.vscode.cmd: code --new-window --wait --diff "$LOCAL" "$REMOTE"
  merge.tool: vscode
  mergetool.vscode.cmd: code --new-window --wait --merge "$LOCAL" "$REMOTE" "$BASE" "$MERGED"
  mergetool.vscode.trustExitCode: true
  mergetool.keepBackup: false

iterm2_profiles_repo: https://github.com/apt-itude/iterm2-profiles.git

homebrew_formulae:
  coreutils:
  fff:
  gh:
  homeport/tap/dyff:
  htop:
  k9s:
  poetry:
  watch:
  wget:
  yq:

homebrew_casks:
  1password:
  amethyst:
  arc:
  flux:
  font-inconsolata-go-nerd-font:
  google-chrome:
  google-drive:
  hiddenbar:
  insomnia:
  notion:
  signal:
  spotify:
  sublime-text:
  ticktick:
  visual-studio-code:

zsh_aliases:
  show-files: defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app
  hide-files: defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app

zinit_plugins:
  apt-itude/zsh-things:
    multisrc: plugins/{macos-gnu-utils,dircolors}.zsh

macos_defaults:
  NSGlobalDomain:
    com.apple.swipescrolldirection:
      type: bool
      value: false
  com.apple.dock:
    autohide:
      type: bool
      value: true
    # Minimize apps to icon instead of near downloads
    minimize-to-application:
      type: bool
      value: true
    # Disable rearranging spaces automatically
    mru-spaces:
      type: bool
      value: false
    # Don't show recent applications
    show-recents:
      type: bool
      value: false
