git_config_global:
  # Diff and merge tools
  core.editor: subl -n --wait
  diff.tool: sublimerge
  difftool.sublimerge.cmd: "subl -n --wait \"$LOCAL\" \"$REMOTE\" --command \"sublimerge_diff_views {\\\"left_read_only\\\": true, \\\"right_read_only\\\": true}\""
  merge.tool: sublimerge
  mergetool.sublimerge.cmd: subl -n --wait "$REMOTE" "$BASE" "$LOCAL" "$MERGED" --command "sublimerge_diff_views"
  mergetool.sublimerge.trustExitCode: False

iterm2_profiles_repo: https://github.com/apt-itude/iterm2-profiles.git

homebrew_taps:
  homebrew/cask-fonts:

homebrew_formulae:
  coreutils:
  fff:
  gh:
  htop:
  poetry:
  wget:

homebrew_casks:
  1password:
  alfred:
  amethyst:
  flux:
  font-inconsolata-go-nerd-font:
  google-chrome:
  google-drive:
  insomnia:
  notion:
  signal:
  spotify:
  sublime-text:
  ticktick:
  visual-studio-code:

zsh_aliases:
  show-files: defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app
  hide-files: defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app

zplug_packages:
  apt-itude/zsh-things:
    use: plugins/{macos-gnu-utils,dircolors}.zsh

macos_defaults:
  com.apple.dock:
    autohide:
      type: bool
      value: true
    # Disable rearranging spaces automatically
    mru-spaces:
      type: bool
      value: false
