git_config_global:
  user.email: alex.thompson@semgrep.com

homebrew_taps:
  returntocorp/infra:
    url: git@github.com:returntocorp/homebrew-infra.git

homebrew_formulae:
  awscli:
  homeport/tap/dyff:
  Noovolari/brew/leapp-cli-darwin-arm64:
  okta-aws-cli:
  returntocorp/infra/kubectl:
  returntocorp/infra/kustomize:

homebrew_casks:
  aws-vpn-client:
  docker:
  leapp:
  session-manager-plugin:
