---
- hosts: macs
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: zsh
      tags: ['shell', 'zsh']
    - role: zplug
      tags: ['shell', 'zsh', 'zplug']
    - role: git
      tags: ['git']
    - role: pyenv
      tags: ['pyenv']
    - role: rbenv
      tags: ['rbenv']
    - role: iterm2
      tags: ['iterm2']
  tasks:
    - name: Configure GNU utils for macOS
      tags: ['shell', 'zsh']
      copy:
        src: zshrc.d/macos-gnu-utils
        dest: "{{ zshrc_dir }}/"
