---
- hosts: all
  roles:
    - role: zsh
      tags: ['shell', 'zsh']
    - role: zplug
      tags: ['shell', 'zsh', 'zplug']
    - role: git
      tags: ['git']
    - role: direnv
      tags: ['direnv']
    - role: vscode
      tags: ['vscode']

- hosts: python
  roles:
    - role: pyenv
      tags: ['pyenv']

- hosts: ruby
  roles:
    - role: rbenv
      tags: ['rbenv']

- hosts: go
  roles:
    - role: go
      tags: ['go']

- hosts: macs
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: macos-defaults
      tags: ['macos-defaults', 'defaults']
    - role: iterm2
      tags: ['iterm2']
