---
- hosts: all
  roles:
    - role: zsh
      tags: ['shell', 'zsh']
    - role: zplug
      tags: ['shell', 'zsh', 'zplug']
    - role: git
      tags: ['git']
    - role: pyenv
      tags: ['pyenv']
    - role: rbenv
      tags: ['rbenv']

- hosts: macs
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: iterm2
      tags: ['iterm2']
