---
- hosts: 128-mac
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: git
      tags: ['git']
    - role: pyenv
      tags: ['pyenv']
    - role: rbenv
      tags: ['rbenv']
    - role: iterm2
      tags: ['iterm2']
