---
- name: Ensuring base dotfiles exist
  copy:
    src: "{{ item }}"
    dest: ~/
  loop:
    - .bash_profile
    - .bashrc
    - .bash_aliases
    - .bash_prompt
    - .dircolors

- name: Ensuring git-prompt exist
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: ~/.git-prompt
    mode: 0400

- name: Applying MacOS-specific configuration
  block:
    - name: Ensuring MacOS-specific dotfiles exist
      copy:
        src: "{{ item }}"
        dest: ~/
      loop:
        - .bashrc.macos
        - .bash_aliases.macos

  when: ansible_os_family == "Darwin"
