---
- name: Install VSCode user repository
  git:
    repo: "{{ vscode_user_repo }}"
    dest: "{{ vscode_user_dir }}"

- name: Check for VSCode user settings
  stat:
    path: "{{ vscode_user_dir }}/settings.json"
  register: vscode_user_settings_file

- name: Check for VSCode user keybindings
  stat:
    path: "{{ vscode_user_dir }}/keybindings.json"
  register: vscode_user_keybindings_file

- name: Determine application config directory
  set_fact:
    app_config_directory: "{{ ansible_env.HOME }}/Library/Application Support"
  when: ansible_os_family == 'Darwin'

- name: Link VSCode user settings
  file:
    src: "{{ vscode_user_settings_file.stat.path }}"
    dest: "{{ app_config_directory }}/Code/User/settings.json"
    state: link
    force: true
  when: vscode_user_settings_file.stat.isreg

- name: Link VSCode user keybindings
  file:
    src: "{{ vscode_user_keybindings_file.stat.path }}"
    dest: "{{ app_config_directory }}/Code/User/keybindings.json"
    state: link
    force: true
  when: vscode_user_keybindings_file.stat.isreg
