---
- name: List installed VSCode extensions
  command:
    cmd: "{{ vscode_executable }} --list-extensions"
  register: vscode_installed_extensions_result

- name: Parse installed VSCode extensions output
  set_fact:
    vscode_installed_extensions: "{{ vscode_installed_extensions_result.stdout_lines }}"

- name: Install VSCode extension
  command:
    cmd: "{{ vscode_executable }} --install-extension {{ item.name }}"
  loop: |
    {{ vscode_extensions | dict2items(key_name='name', value_name='config') }}
  when: item.name not in vscode_installed_extensions
