---
- name: Ensure files in .zshenv.d get sourced
  blockinfile:
    path: ~/.zshenv
    block: |
      if [ -f "/etc/profile" ]; then
          source "/etc/profile"
      fi

      for subrc in {{ zshenv_dir }}/*(.N); do
          [ -f "$subrc" ] && source "$subrc"
      done
    insertbefore: BOF
    marker: "# {mark} BLOCK MANAGED BY DEV-ENV VIA ANSIBLE"
    create: true

- name: Ensure files in .zshrc.d get sourced
  blockinfile:
    path: ~/.zshrc
    block: |
      for subrc in {{ zshrc_dir }}/*(.N); do
          [ -f "$subrc" ] && source "$subrc"
      done
    insertbefore: BOF
    marker: "# {mark} BLOCK MANAGED BY DEV-ENV VIA ANSIBLE"
    create: true

- name: Create ZSH config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ zshenv_dir }}"
    - "{{ zshrc_dir }}"

- name: Configure ZSH aliases
  template:
    src: aliases.j2
    dest: "{{ zshrc_dir }}/aliases"
  vars:
    aliases: "{{ zsh_aliases }}"

- name: Configure ZSH options
  template:
    src: options.j2
    dest: "{{ zshrc_dir }}/options"
  vars:
    options: "{{ zsh_options }}"

- name: Configure ZSH variables
  template:
    src: variables.j2
    dest: "{{ zshrc_dir }}/variables"
  vars:
    variables: "{{ zsh_variables }}"
