---
- name: Ensure files in .zshenv.d get sourced
  blockinfile:
    path: ~/.zshenv
    block: |
      if [ -f "/etc/profile" ]; then
          source "/etc/profile"
      fi

      for subrc in {{ zshenv_dir }}/*(.N); do
          [ -f "$subrc" ] && source "$subrc"
      done
    insertbefore: BOF
    marker: "# {mark} BLOCK MANAGED BY DEV-ENV VIA ANSIBLE"
    create: true

- name: Configure .zshrc
  blockinfile:
    path: ~/.zshrc
    block: "{{ lookup('template', 'zshrc.j2') }}"
    insertbefore: BOF
    marker: "# {mark} BLOCK MANAGED BY DEV-ENV VIA ANSIBLE"
    create: true

- name: Create ZSH config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ zshenv_dir }}"
    - "{{ zshrc_dir }}"
