---
- name: Update Homebrew
  homebrew:
    update_homebrew: true

- name: Configure Taps
  homebrew_tap:
    name: "{{ item.name }}"
    state: "{{ item.config.state | default('present') }}"
    url: "{{ item.config.url | default(omit) }}"
  loop: "{{ homebrew_taps | dict2items(key_name='name', value_name='config') }}"

- name: Install Formulae
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.config.state | default('present') }}"
  loop: "{{ homebrew_formulae | dict2items(key_name='name', value_name='config') }}"

- name: Install Casks
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.config.state | default('present') }}"
  loop: "{{ homebrew_casks | dict2items(key_name='name', value_name='config') }}"
