---
- name: Update Homebrew
  homebrew:
    update_homebrew: true

- name: Configure Taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop: "{{ ['homebrew/core', 'homebrew/cask'] + homebrew_taps }}"

- name: Install Formulae
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulae }}"

- name: Install Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"
