---
- include: install.yml

- name: Installing versions
  command: pyenv install "{{ item }}"
  args:
    creates: "{{ pyenv_root }}/versions/{{ item }}"
  loop: "{{ pyenv_installed_versions }}"

- name: Setting versions
  template:
    src: versions.j2
    dest: "{{ pyenv_root }}/version"
  vars:
    versions: "{{ pyenv_global_versions }}"

- name: Enabling pyenv in ZSH
  template:
    src: zshenv.d/pyenv.j2
    dest: "{{ zshenv_dir }}/pyenv"
