---
- include_tasks: install.yml

- name: Installing versions
  command: rbenv install "{{ item.version }}"
  args:
    creates: "{{ rbenv_root }}/versions/{{ item.version }}"
  loop: "{{ rbenv_versions | dict2items(key_name='version', value_name='config') }}"

- name: Set global versions
  template:
    src: versions.j2
    dest: "{{ rbenv_root }}/version"
  vars:
    versions: |
      {{
        rbenv_versions |
        dict2items(key_name='version', value_name='config') |
        rejectattr('config', 'none') |
        selectattr('config.global', 'equalto', true) |
        map(attribute='version') |
        sort(reverse=True)
      }}

- name: Enabling rbenv in ZSH
  template:
    src: init.j2
    dest: ~/.dev-env/rbenv/init.sh

- name: Configure ZSH to initialize rbenv
  blockinfile:
    path: ~/.zshrc
    block: |
      if [ -f ~/.dev-env/rbenv/init.sh ]; then
          source ~/.dev-env/rbenv/init.sh
      fi
    marker: "# {mark} BLOCK MANAGED BY DEV-ENV: initialize rbenv"
    create: true
